name: deploy gh-pages
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and deploy gh-pages
    env:
      MY_SECRET   : ${{secrets.commit_secret}}
      USER_NAME   : githubaction
      USER_EMAIL  : githubaction@fake.com
      PUBLISH_DIR : ./dist
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm install
    - name: git config
      run: |
        git config --local user.name $USER_NAME
        git config --local user.email $USER_EMAIL
        git remote add origin https://$MY_SECRET@github.com/$GITHUB_REPOSITORY.git
    - name: deploy to gh-pages
      run: |
        npm run gh
        echo 🤘 deploy gh-pages complete.        
